# -*- coding: utf-8 -*-
"""Regression Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsfH2hO4cvmr7AYvfqu07i5KUSw3GrVI
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/student-por.csv')

df.head()

df.isnull().sum()

df.info()

df.describe()

missing_values = df.isnull().sum()
print(missing_values)

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(df['age'], kde=True)
plt.show()
sns.boxplot(x='G3', data=df)
plt.show()

sns.countplot(x='sex', data=df, hue='G3')
plt.show()
sns.countplot(x='school', data=df, hue='G3')
plt.show()
print(df.columns)  # Print the column names of your DataFrame to check if 'G3' is present

